### ISSUE TITLE
Issue with Umaluts

### ISSUE THREAD

**Issue by Zettt** [dmarmor/osx-chrome-ssb-gui#8]
I'm sorry, but Umlauts are an issue here too. When creating an app with Ü, e.g. [Der Übercast](http://derubercast.com), the app gives this error here:

```
Creation failed: Traceback (most recent call last):
  File "/Users/zettt/Desktop/ÜÄÖ.app.23551/Contents.25369/Resources/Scripts/strings.py", line 62, in <module>
    outtext.append(m.group(1) + curname + m.group(4))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 1: ordinal not in range(128)
```

Let me know if you need additional information.

**Comment by Zettt** [comment]
*Info.plist* entries like *Bundle display name* and *Bundle name* can be changed afterwards and they don't seem to affect the SSB. I haven't tried to change the Bundle Identifier though, that seemed too risky.

**Comment by dmarmor** [comment]
I'll look into this. I've managed to get the same error on my system, so that's a start.

Meantime, if you do want to temporarily change the bundle identifier, just make sure to also change it in <app>/Contents/Resources/Scripts.config.sh. (Though in the next release of the app, the bundle identifiers are all going to change, so don't rely on it staying as whatever you've set it.)

**Comment by Zettt** [comment]
No worries, I can deal with those kind of issues.

**Comment by dmarmor** [comment]
Hey, I forgot to write back about this. Unicode is totally mysterious to me, but by trial and error I managed to fix it so that I was able to create an SSB with umlauts in the name. This fix will be in the new release too.

I have no idea how robust the solution is, but it's at least not crashing any more! I'll close the issue for now. We can re-open if it seems shaky when the new release is up and you have a chance to test it. Thanks!
